apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
spec:
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: cache
        image:  rasoul5g/drl_cache:latest
        imagePullPolicy: Always
        envFrom: 
        ports:
        - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  name: cache
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: cache
  type: NodePort

